#!/usr/bin/env bash
# Process a single `missing-country` issue: research, validate, commit, open PR.
#
# Required env:
#   GH_TOKEN, ANTHROPIC_API_KEY  — credentials
#   ISSUE_NUMBER                 — issue to process
#   GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID — for log links in failure comments
#
# Exits 0 whether the research succeeded or was gracefully skipped; only exits
# non-zero on unrecoverable environment problems (e.g. bad issue body).

set -euo pipefail

N="${ISSUE_NUMBER:?ISSUE_NUMBER is required}"
BRANCH="auto-policy/issue-${N}"

echo "::group::Issue #$N"

# Skip if branch / PR already exists — avoids duplicate PRs on repeated runs.
if git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
  echo "Branch $BRANCH already exists — skipping."
  echo "::endgroup::"
  exit 0
fi

gh issue view "$N" --json body -q .body > /tmp/issue-body.md
COUNTRY_CODE=$(awk '/^country_code:/{print $2; exit}' /tmp/issue-body.md)
COUNTRY_NAME=$(awk '/^country_name:/{sub(/^country_name:[[:space:]]*/, ""); print; exit}' /tmp/issue-body.md)

if [ -z "$COUNTRY_CODE" ] || [ -z "$COUNTRY_NAME" ]; then
  echo "Issue #$N frontmatter missing country_code or country_name — skipping."
  gh issue comment "$N" --body "Auto-research skipped: issue body is missing the required YAML frontmatter fields (country_code, country_name)."
  echo "::endgroup::"
  exit 0
fi

git checkout -b "$BRANCH" main

# Run research script; capture stdout for PR body sources section
if ! ISSUE_BODY_PATH=/tmp/issue-body.md REPO_ROOT=. \
     python3 .github/scripts/research.py > /tmp/sources.md 2>/tmp/research.err; then
  echo "Research failed for issue #$N"
  cat /tmp/research.err
  ERR_TAIL=$(tail -20 /tmp/research.err | tr '\n' ' ' | cut -c1-500)
  RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
  gh issue comment "$N" --body "Auto-research failed. See [workflow logs]($RUN_URL). Last error: \`$ERR_TAIL\`"
  git checkout main
  git branch -D "$BRANCH" || true
  echo "::endgroup::"
  exit 0
fi

# Local schema validation as a second safety net before commit.
check-jsonschema --schemafile schema/rule.schema.json "rules/${COUNTRY_CODE}_SG.json"
check-jsonschema --schemafile schema/document.schema.json "documents/${COUNTRY_CODE}.json"
check-jsonschema --schemafile schema/manifest.schema.json manifest.json

git add manifest.json "rules/${COUNTRY_CODE}_SG.json" "documents/${COUNTRY_CODE}.json"

COMMIT_MSG_FILE=$(mktemp)
{
  echo "Auto-research: ${COUNTRY_NAME} (${COUNTRY_CODE})"
  echo ""
  echo "Generated from issue #${N}."
} > "$COMMIT_MSG_FILE"
git commit -F "$COMMIT_MSG_FILE"
rm -f "$COMMIT_MSG_FILE"
git push origin "$BRANCH"

# Build PR body in a file — avoids YAML / shell quoting hell.
PR_BODY_FILE=$(mktemp)
{
  echo "Closes #${N}"
  echo ""
  echo "Autonomous research run generated policy JSON for **${COUNTRY_NAME}** (\`${COUNTRY_CODE}\`)."
  echo ""
  echo "Review checklist before merging:"
  echo ""
  echo "- [ ] Verify \`thresholdDays\` / \`windowDays\` on each rule against cited sources"
  echo "- [ ] Confirm every \`actionStep.url\` points to an official source (.gov, embassy, CVASC, etc.)"
  echo "- [ ] Sanity-check the tax residency day counts"
  echo "- [ ] Check that \`applicableVisaTypes\` scoping is correct"
  echo ""
  cat /tmp/sources.md
  echo ""
  echo "---"
  echo "_Generated by \`.github/scripts/research.py\` using Claude API. Schema-validated before commit._"
} > "$PR_BODY_FILE"

gh pr create --base main --head "$BRANCH" \
  --title "Auto-research: ${COUNTRY_NAME} (${COUNTRY_CODE})" \
  --body-file "$PR_BODY_FILE" \
  --label auto-policy-update
rm -f "$PR_BODY_FILE"

# Mark issue so future scheduled runs skip it.
gh issue edit "$N" --add-label awaiting-review
gh issue comment "$N" --body "Auto-research complete — PR opened for review."

git checkout main
echo "::endgroup::"
